#!/bin/bash

PROJECT=z3
PROJECT_VERSION=4.4.0
PACKAGE_REVISION=1


PACKAGING_ROOT="${HOME}/debian"
PACKAGE_NAME="${PROJECT}_${PROJECT_VERSION}-${PACKAGE_REVISION}"
PACKAGE_PATH="${PACKAGING_ROOT}/${PACKAGE_NAME}"
PACKAGE_META="${PACKAGE_PATH}/DEBIAN"

# Create work directory.
mkdir -p "${PACKAGE_PATH}"

# Create directory structure.
PREFIX=/usr
mkdir -p ${PACKAGE_PATH}${PREFIX}/bin

# Copy files.
cp ${PREFIX}/bin/z3 ${PACKAGE_PATH}${PREFIX}/bin/z3

# Copy metadata.
mkdir -p "${PACKAGE_META}"
cp ${PACKAGING_ROOT}/control "${PACKAGE_META}"

# Build package.
cd ${PACKAGING_ROOT} && dpkg-deb --build "${PACKAGE_NAME}"
