#!/bin/bash

function initialize () {

  # Set variables.
  PACKAGING_ROOT="${HOME}/debian"
  PACKAGE_NAME="${PROJECT}_${PROJECT_VERSION}-${PACKAGE_REVISION}"
  PACKAGE_PATH="${PACKAGING_ROOT}/${PACKAGE_NAME}"
  PACKAGE_META_TARGET="${PACKAGE_PATH}/DEBIAN"
  PACKAGE_META_SOURCE="${PACKAGING_ROOT}/${PROJECT}"

  # Create work directory.
  mkdir -p "${PACKAGE_PATH}"
}

# Package Z3.

PROJECT=z3
PROJECT_VERSION=4.4.0
PACKAGE_REVISION=1

initialize

# Create directory structure.
PREFIX=/usr
mkdir -p ${PACKAGE_PATH}${PREFIX}/bin

# Copy files.
cp ${PREFIX}/bin/z3 ${PACKAGE_PATH}${PREFIX}/bin/z3

# Copy metadata.
mkdir -p "${PACKAGE_META_TARGET}"
cp ${PACKAGE_META_SOURCE}/* "${PACKAGE_META_TARGET}"

# Build package.
cd ${PACKAGING_ROOT} && dpkg-deb --build "${PACKAGE_NAME}"

# Package Boogie.

PROJECT=boogie
PROJECT_VERSION=2015.06.10
PACKAGE_REVISION=1

initialize

# Create directory structure.
PREFIX=/usr
mkdir -p ${PACKAGE_PATH}${PREFIX}/bin
mkdir -p ${PACKAGE_PATH}${PREFIX}/lib

# Copy files.
cp ${PREFIX}/bin/boogie ${PACKAGE_PATH}${PREFIX}/bin/boogie
cp -r ${PREFIX}/lib/boogie ${PACKAGE_PATH}${PREFIX}/lib/boogie

# Copy metadata.
mkdir -p "${PACKAGE_META_TARGET}"
cp ${PACKAGE_META_SOURCE}/* "${PACKAGE_META_TARGET}"

# Build package.
cd ${PACKAGING_ROOT} && dpkg-deb --build "${PACKAGE_NAME}"

# Package Viper

PROJECT=viper
PROJECT_VERSION=0.1
PACKAGE_REVISION=1

initialize

# Create directory structure.
PREFIX=/usr
mkdir -p ${PACKAGE_PATH}${PREFIX}/bin
mkdir -p ${PACKAGE_PATH}${PREFIX}/lib/viper

# Copy files.
cp ${PACKAGE_META_SOURCE}/silicon ${PACKAGE_PATH}${PREFIX}/bin/silicon
#cp ${PACKAGE_META_SOURCE}/carbon ${PACKAGE_PATH}${PREFIX}/bin/carbon
#cp ${PACKAGE_META_SOURCE}/chalice2silver ${PACKAGE_PATH}${PREFIX}/bin/chalice2silver
cp "${HOME}/source/chalice2silver/target/scala-2.11/chalice2sil.jar" ${PACKAGE_PATH}${PREFIX}/lib/viper/viper.jar

# Copy metadata.
mkdir -p "${PACKAGE_META_TARGET}"
cp ${PACKAGE_META_SOURCE}/control "${PACKAGE_META_TARGET}"

# Build package.
cd ${PACKAGING_ROOT} && dpkg-deb --build "${PACKAGE_NAME}"
